import { NodeRaw } from "@src/node/raw"
import type { INode, BuildArtifact } from "@src/type"

export const RAW = "<!-- Generated by HTMLForge (https://github.com/tlonny/htmlforge) -->"

export class HTMLNodeSignature implements INode {

    private readonly raw : NodeRaw

    constructor() {
        this.raw = new NodeRaw(RAW)
    }

    build() : Iterable<BuildArtifact> {
        return this.raw.build()
    }
}
