import type { INode, BuildArtifact } from "@src/type"

const SIGNATURE = "<!-- Generated by HTMLForge (https://github.com/tlonny/htmlforge) -->"

export class HTMLNodeSignature implements INode {

    *build() : Iterable<BuildArtifact> {
        yield {
            buildArtifactType: "RAW",
            raw: SIGNATURE
        }
    }
}
